js:
  jquery:
    - vendor/jquery/jquery-1.5.js
    
  extjs:
    - vendor/ext/adapter/jquery/ext-jquery-adapter-debug.js
    - vendor/ext/ext-all.js
    - vendor/ext/ux/*.js

  rwiki:
    - Rwiki/**/*.js
    - Rwiki.js

css:
  core:
    - *.css
