javascripts:
  jquery:
    - vendor/jquery/jquery-1.5

  extjs:
    - vendor/ext/ux/Ext.ux.MessageBox.flash
    - vendor/ext/ux/StatusBar
    - vendor/ext/ux/TabCloseMenu

  markitup:
    - vendor/markitup/jquery.markitup

  rwiki:
    - Rwiki/Data/Page
    - Rwiki/Data/PageManager
    - Rwiki/Editor/EditorPanel
    - Rwiki/Search/Window
    - Rwiki/Search/FuzzyFinderWindow
    - Rwiki/Search/TextSearchWindow
    - Rwiki/Tabs/PageTab
    - Rwiki/Tabs/Toolbar
    - Rwiki/Tree/Loader
    - Rwiki/Tree/Menu
    - Rwiki/Tree/Node
    - Rwiki/AboutDialog
    - Rwiki/Button
    - Rwiki/Debug
    - Rwiki/EditorWindow
    - Rwiki/Mask
    - Rwiki/NavigationPanel
    - Rwiki/TabPanel
    - Rwiki/TocPanel
    - Rwiki/TreePanel
    - Rwiki

stylesheets:
  extjs:
    - vendor/ext/ext-all
    - vendor/ext/css/Ext.ux.MessageBox.flash

  markitup:
    - vendor/markitup/skins/markitup/style
    - vendor/markitup/sets/textile/style

  rwiki:
    - Rwiki/page
    - Rwiki/coderay
    - Rwiki/markitup
    - style
