js:
  jquery:
    - vendor/jquery/jquery-1.5.js
    
  extjs:
    - vendor/ext/adapter/jquery/ext-jquery-adapter-debug.js
    - vendor/ext/ext-all.js
    - vendor/ext/ux/*.js

  markitup:
    - vendor/markitup/jquery.markitup.js

  rwiki:
    - Rwiki/**/*.js
    - Rwiki.js

css:
  extjs:
    - vendor/ext/css/ext-all.css

  markitup:
    - vendor/markitup/skins/markitup/style.css
    - vendor/markitup/sets/textile/style.css

  rwiki:
    - Rwiki/**/*.css
    - style.css
