javascripts:
  jquery:
    - vendor/jquery/jquery-1.5
    
  extjs:
    - vendor/ext/adapter/jquery/ext-jquery-adapter-debug
    - vendor/ext/ext-all
    - vendor/ext/ux/StatusBar
    - vendor/ext/ux/TabCloseMenu

  markitup:
    - vendor/markitup/jquery.markitup

  rwiki:
    - Rwiki/Data/Node
    - Rwiki/Data/NodeManager
    - Rwiki/Editor/EditorPanel
    - Rwiki/Tabs/PageTab
    - Rwiki/Tree/Filter
    - Rwiki/Tree/Loader
    - Rwiki/Tree/Menu
    - Rwiki/Tree/Node
    - Rwiki/Tree/Toolbar
    - Rwiki/EditorWindow
    - Rwiki/FuzzyFinderWindow
    - Rwiki/NavigationPanel
    - Rwiki/TabPanel
    - Rwiki/TreePanel
    - Rwiki

stylesheets:
  extjs:
    - vendor/ext/css/ext-all

  markitup:
    - vendor/markitup/skins/markitup/style
    - vendor/markitup/sets/textile/style

  rwiki:
    - Rwiki/coderay
    - Rwiki/markitup
    - Rwiki/page
    - style
